name: Tests VHDL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GHDL
      run: sudo apt-get update && sudo apt-get install -y ghdl

    - name: Install dependencies
      run: make

    - name: Run test
      run: make test
